export function piTeamsHelp(): string {
	return [
		"pi-crew commands:",
		"",
		"Core:",
		"- Agent can use the `team` tool autonomously; slash commands are manual controls.",
		"- /teams — list teams, workflows, agents, recent runs",
		"- /team-run [--team=name] [--workflow=name] [--async] [--worktree] <goal>",
		"- /team-status <runId>",
		"- /team-summary <runId>",
		"- /team-resume <runId>",
		"- /team-cancel <runId>",
		"- /team-retry <runId> [taskId]",
		"- /team-respond <runId> <taskId|--all> <message>",
		"- /team-follow-up <runId> <taskId> <prompt>",
		"- /team-goal — autonomous goal loop (sub-actions: start/status/pause/resume/stop/step/clear)",
		"- /workflows — list static + dynamic workflows",
		"",
		"Inspection:",
		"- /team-events <runId>",
		"- /team-artifacts <runId>",
		"- /team-result <runId> [taskId]",
		"- /team-transcript <runId> [taskId]",
		"- /team-worktrees <runId>",
		"- /team-api <runId> <operation> [key=value]",
		"- /team-metrics [filter]",
		"- /team-dashboard",
		"- /team-mascot",
		"",
		"Maintenance:",
		"- /team-manager — interactive menu (alias: /team-cleanup-menu)",
		"- /team-forget <runId> --confirm [--force]",
		"- /team-prune --keep=20 --confirm",
		"- /team-invalidate <runId>",
		"",
		"Skills:",
		"- /skill-list [--json] — list builtin skill templates",
		"- /skill-create <template-id> [--var key=value...] [--project]",
		"",
		"Portability:",
		"- /team-export <runId>",
		"- /team-import <path-to-run-export.json>",
		"- /team-imports",
		"",
		"Diagnostics & config:",
		"- /team-doctor",
		"- /team-validate",
		"- /team-init [--copy-builtins] [--overwrite]",
		"- /team-config [key=value] [--unset=key.path] [--project]",
		"- /team-settings [list|get <key>|set <key> <value>|unset <key>|path|scope]",
		"- /team-autonomy [status|on|off|manual|suggested|assisted|aggressive]",
		"- /team-help",
		"",
		"Non-team commands: /schedules [log <jobId-or-name>], /crew-view <runId> <taskId>, /crew-back, /team-vibes [on|off], /crew-brief [on|off|status]",
		"",
		"Goal loops (P0/P1 — autonomous goal loop):",
		"- team action='goal' config.subAction='start' config.objective='...' config.evaluatorModel='...' [config.maxTurns=20] [budgetTotal=N]",
		"- team action='goal' config.subAction='status' [config.goalId=<id>]",
		"- team action='goal' config.subAction='pause|resume|stop|step|clear' config.goalId=<id>",
		"",
		"Dynamic workflows (P2/P3 — JS-script orchestration):",
		"- Place a .dwf.ts under .crew/workflows/ then: team action='run' workflow='<name>' goal='...'",
		"- team action='workflow-list'",
		"- team action='workflow-get' config.name='<name>'",
		"- team action='workflow-create' confirm=true config.name='<name>' config.script='<.dwf.ts source>'  (USER-initiated only; ACE-gated)",
		"- team action='workflow-save' config.name='<name>' config.script='<source>'",
		"- team action='workflow-delete' confirm=true config.name='<name>'",
		"- /workflows — list dynamic workflows",
		"",
		"Real child workers are enabled by default. Use runtime.mode=scaffold or executeWorkers=false only for dry runs.",
	].join("\n");
}
